Repository adaptlearning/adapt-contrib-assessment, pull requests merged in 2022-09, with the labels that each got.

#174 Fix: Logging instances of question bank misuse
  .github/pull_request_template.md
  js/adapt-assessmentArticleModel.js
  js/adapt-assessmentQuestionBank.js
Labels: enhancement

#176 Fix: Removed deprecated behaviour (fixes #175)
  js/adapt-assessmentArticleModel.js
Labels: bug

#179 Fix: Defensive sanity check of assessment data (fixes #178)
  js/adapt-assessmentArticleModel.js
Labels: breaking
